# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180409_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postype',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='created',
        ),
        migrations.AddField(
            model_name='question',
            name='body',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
